/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ASUS TUF GAMING
 */
public class viewLogindatos extends javax.swing.JFrame {

    /**
     * Creates new form viewLogindatos
     */
    public viewLogindatos() {
        initComponents();
    }

    public JLabel getLbladmin() {
        return lbladmin;
    }

    public void setLbladmin(JLabel lbladmin) {
        this.lbladmin = lbladmin;
    }
    
//////////
    public JButton getBt_iniciar() {
        return bt_iniciar;
    }

    public void setBt_iniciar(JButton bt_iniciar) {
        this.bt_iniciar = bt_iniciar;
    }

    public JButton getBt_registrarse() {
        return bt_registrarse;
    }

    public void setBt_registrarse(JButton bt_registrarse) {
        this.bt_registrarse = bt_registrarse;
    }

    public JButton getBt_salir() {
        return bt_salir;
    }

    public void setBt_salir(JButton bt_salir) {
        this.bt_salir = bt_salir;
    }
   
    public JTextField getTxtusuarioLogin() {
        return txtusuarioLogin;
    }

    public void setTxtusuarioLogin(JTextField txtusuarioLogin) {
        this.txtusuarioLogin = txtusuarioLogin;
    }

    public JPasswordField getTxtcontraseñaLogin() {
        return txtcontraseñaLogin;
    }

    public void setTxtcontraseñaLogin(JPasswordField txtcontraseñaLogin) {
        this.txtcontraseñaLogin = txtcontraseñaLogin;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusuarioLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bt_iniciar = new javax.swing.JButton();
        bt_registrarse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtcontraseñaLogin = new javax.swing.JPasswordField();
        lbladmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 190, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USUARIO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtusuarioLogin.setBackground(new java.awt.Color(1, 190, 255));
        txtusuarioLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtusuarioLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtusuarioLogin.setText("Usuario");
        txtusuarioLogin.setToolTipText("");
        txtusuarioLogin.setBorder(null);
        jPanel2.add(txtusuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 349, 20));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 340, 20));

        bt_iniciar.setBackground(new java.awt.Color(255, 153, 153));
        bt_iniciar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        bt_iniciar.setText("INICIAR SESIÓN");
        bt_iniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(bt_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 290, 40));

        bt_registrarse.setBackground(new java.awt.Color(255, 153, 153));
        bt_registrarse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarse.setText("REGISTRARSE");
        bt_registrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(bt_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 130, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TIUTLOLETRAS2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 400, 90));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 340, 20));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 340, 20));

        txtcontraseñaLogin.setBackground(new java.awt.Color(1, 190, 255));
        txtcontraseñaLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtcontraseñaLogin.setText("jPasswordField1");
        txtcontraseñaLogin.setBorder(null);
        jPanel2.add(txtcontraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 340, 30));

        lbladmin.setText("administrador");
        jPanel2.add(lbladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_salir.setBackground(new java.awt.Color(255, 153, 153));
        bt_salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_salir.setForeground(new java.awt.Color(255, 255, 255));
        bt_salir.setText("SALIR");
        jPanel1.add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NutriaLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 660, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogindatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogindatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogindatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogindatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogindatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_iniciar;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JPasswordField txtcontraseñaLogin;
    private javax.swing.JTextField txtusuarioLogin;
    // End of variables declaration//GEN-END:variables
}
