/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import kidsgames.ManagerFactory;


/**
 *
 * @author Shalva
 */
public class viewMenuAdmin extends javax.swing.JFrame {

    public viewMenuAdmin() {
        initComponents();
    }

    public JMenuItem getAdmin() {
        return admin;
    }

    public void setAdmin(JMenuItem admin) {
        this.admin = admin;
    }

    public JMenuItem getEstu() {
        return estu;
    }

    public void setEstu(JMenuItem estu) {
        this.estu = estu;
    }

    public JMenu getJuego() {
        return juego;
    }

    public void setJuego(JMenu juego) {
        this.juego = juego;
    }

    public JMenuItem getProfe() {
        return profe;
    }

    public void setProfe(JMenuItem profe) {
        this.profe = profe;
    }

    public JMenu getPuntaje() {
        return puntaje;
    }

    public void setPuntaje(JMenu puntaje) {
        this.puntaje = puntaje;
    }

    public JMenu getRegistro() {
        return registro;
    }

    public void setRegistro(JMenu registro) {
        this.registro = registro;
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }
  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        registro = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        profe = new javax.swing.JMenuItem();
        estu = new javax.swing.JMenuItem();
        juego = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        puntaje = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NutriaTitulo.png"))); // NOI18N

        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 670));

        registro.setText("Registro");

        admin.setText("Administrador");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        registro.add(admin);

        profe.setText("Profesor");
        registro.add(profe);

        estu.setText("Estudiante");
        registro.add(estu);

        jMenuBar1.add(registro);

        juego.setText("Juegos");

        jMenuItem4.setText("Juego de memoria");
        juego.add(jMenuItem4);

        jMenuBar1.add(juego);

        puntaje.setText("Puntaje");
        jMenuBar1.add(puntaje);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenuItem estu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu juego;
    private javax.swing.JMenuItem profe;
    private javax.swing.JMenu puntaje;
    private javax.swing.JMenu registro;
    // End of variables declaration//GEN-END:variables
}
