/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Subvista;

/**
 *
 * @author Shalva
 */
public class viewPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewPersona
     */
    public viewPersona() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegCrearAdmins = new javax.swing.JButton();
        btnRegProfes = new javax.swing.JButton();
        btnRegEstud = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegCrearAdmins.setBackground(new java.awt.Color(255, 153, 153));
        btnRegCrearAdmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-add-free-icon-font.png"))); // NOI18N
        getContentPane().add(btnRegCrearAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 120));

        btnRegProfes.setBackground(new java.awt.Color(255, 153, 153));
        btnRegProfes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnRegProfes.setForeground(new java.awt.Color(51, 0, 0));
        btnRegProfes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man-head-free-icon-font.png"))); // NOI18N
        btnRegProfes.setText("+");
        getContentPane().add(btnRegProfes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 120));

        btnRegEstud.setBackground(new java.awt.Color(255, 153, 153));
        btnRegEstud.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnRegEstud.setForeground(new java.awt.Color(51, 0, 0));
        btnRegEstud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/child-head-free-icon-font.png"))); // NOI18N
        btnRegEstud.setText("+");
        getContentPane().add(btnRegEstud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 140, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondochido.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 550, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegCrearAdmins;
    private javax.swing.JButton btnRegEstud;
    private javax.swing.JButton btnRegProfes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
